services:
  database:
    image: mysql
    environment:
      MYSQL_DATABASE: sflowdb
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/secret-db
    restart: always
    secrets:
      - secret-db
    volumes:
      - ./db/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    ports:
      - "3306:3306"

secrets:
  secret-db:
    file: ./db/secret-db